name: Run ST Invoice Sync

on:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 10 AM UTC
  workflow_dispatch:       # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ST Invoice Sync
      run: |
        python Invoice-Data-ST.py
